### ISSUE TITLE
INFOGRAFÍA

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/infografia-de-las-librerias-Nayee123#2]
[INFOGRAFIA NAYELI ANAI GONZALEZ LOPEZ.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-Nayee123/files/6308265/INFOGRAFIA.NAYELI.ANAI.GONZALEZ.LOPEZ.pdf)

**Comment by Valentiin01** [comment]
Buen trabajo tienes 20

**Comment by josealfredo79** [comment]
Revisado y bien hecho.
